### ISSUE TITLE
Set container specific tests to run after setup containers

### ISSUE THREAD

**Issue by jananga99** [FYP-Jalien/jalien-setup#40]
1) Setup the environment, Clone the Test Suite and Run container specific tests . (Refer workflow file)
Set a separate flag for this procedure

2) When starting the optimiser , echo its PID

3) When running test suite flag is set, after the test suite run, stop the container and kill the optimiser using above saved PID

**Comment by Malith-19** [comment]
To get the PID we need to start the optimizer in another terminal (when UI flag is true). Unless if we running the optimizer in the main process then there is no way to close it until it finishes.

We need to set UI flag to true once we running the optimizer.
